# action.yml
name: 'Push data to kusto'
description: 'Action to push data to azure data explorer'
outputs:
  name:
    description: "Greeting for a passed name"
runs:
  using: 'docker'
  image: 'Dockerfile'